### ISSUE TITLE
The version bedfe92 for this integration can not be used with HACS

### ISSUE THREAD

**Issue by gstew08** [RobinJ1995/home-assistant-esb-smart-meter-integration#2]
Trying to install this integration through HACS and getting the following error

"The version bedfe92 for this integration can not be used with HACS"

Not sure if it's an issue with HACS or the ESB Smart Meter integration but I've managed to install a different integration no problem.
 Currently running on v2.0.1.

**Comment by gstew08** [comment]
found out it had to be manually installed.

**Comment by colfin22** [comment]
Working? Because I'm not getting any sensors

**Comment by gstew08** [comment]
Sorry, more meant had to be installed manually. 
I'm getting the same error with no sensors. Was going to raise a new issue on it.
